name: Build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:

    strategy:
      matrix:
        include:
          - os: ubuntu-latest
          - os: windows-latest

    runs-on: ${{ matrix.os }}

    steps:

    - uses: actions/checkout@v4

    - name: Install Qt
      uses: jurplel/install-qt-action@v4
      with:
        version: "6.8.2"

    - name: Configure
      run: cmake -B build -DCMAKE_BUILD_TYPE=Release

    - name: Build
      run: cmake --build build --config Release

    - name: Deploy Windows
      if: runner.os == 'Windows'
      shell: cmd
      run: |
        cd build
        windeployqt Release\Counter.exe

    - name: Upload Linux
      if: runner.os == 'Linux'
      uses: actions/upload-artifact@v4
      with:
        name: Counter-Linux
        path: build/Counter

    - name: Upload Windows
      if: runner.os == 'Windows'
      uses: actions/upload-artifact@v4
      with:
        name: Counter-Windows
        path: build/Release/**
